apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml.back --volumes hostPath
      -o hostPath/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: panhandler
  name: panhandler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: panhandler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert -f docker-compose.yml.back --volumes hostPath
          -o hostPath/
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/ph-backend: "true"
        io.kompose.service: panhandler
    spec:
      containers:
      - env:
        - name: CNC_PASSWORD
          value: panme
        - name: CNC_USERNAME
          value: tobias
        image: paloaltonetworks/panhandler
        imagePullPolicy: ""
        name: panhandler
        resources: {}
        
      restartPolicy: Always
      serviceAccountName: ""

status: {}
