apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml.back --volumes hostPath
      -o hostPath/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: panhandler
  name: panhandler
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: panhandler

